### ISSUE TITLE
Fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by florenthemmi** [bcicen/ctop#25]
I have encountered this panic one time. Below the complete stack trace.  
After this panic, the terminal is not usable anymore (cannot type in it).

```
fatal error: concurrent map read and map write

goroutine 27 [running]:
runtime.throw(0x73bc06, 0x21)
	/usr/lib/go/src/runtime/panic.go:596 +0x95 fp=0xc420162ec8 sp=0xc420162ea8
runtime.mapaccess2_faststr(0x6ce980, 0xc42015c0c0, 0xc420156300, 0x40, 0xc420162f80, 0x4063f5)
	/usr/lib/go/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc420162f28 sp=0xc420162ec8
main.(*DockerContainerSource).MustGet(0xc420168180, 0xc420156300, 0x40, 0x1)
	/home/bradley/repos/bcicen/ctop/dockersource.go:109 +0x53 fp=0xc420162f90 sp=0xc420162f28
main.(*DockerContainerSource).Loop(0xc420168180)
	/home/bradley/repos/bcicen/ctop/dockersource.go:102 +0x9d fp=0xc420162fd8 sp=0xc420162f90
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420162fe0 sp=0xc420162fd8
created by main.NewDockerContainerSource
	/home/bradley/repos/bcicen/ctop/dockersource.go:34 +0x148
```

[ctop_stack_trace.txt](https://github.com/bcicen/ctop/files/833353/ctop_stack_trace.txt)

**Comment by bcicen** [comment]
Thanks @florenthemmi. read/write locks have been added in the [latest release](https://github.com/bcicen/ctop/releases/tag/v0.4.1), so this should now be resolved.
