### ISSUE TITLE
[Bug] - Crashes when loading container logs

### ISSUE THREAD

**Issue by ondrovic** [bcicen/ctop#254]
Never had this happen before but when I am attempting to look at the logs for a specific container it crashes and says the following 

```
panic: runtime error: index out of range [1] with length 1 goroutine 32 [running]:
github.com/bcicen/ctop/connector/collector.(*DockerLogs).Stream.func1(0xc00030c018, 0xc000516580, 0xc0002d2660)
        /app/connector/collector/docker_logs.go:52 +0x1f4
created by github.com/bcicen/ctop/connector/collector.(*DockerLogs).Stream
        /app/connector/collector/docker_logs.go:47 +0x278
```
and
```
panic: runtime error: index out of range [1] with length 1

goroutine 167 [running]:
github.com/bcicen/ctop/connector/collector.(*DockerLogs).Stream.func1(0xc00011a068, 0xc0004186a0, 0xc0000943c0)
        /app/connector/collector/docker_logs.go:52 +0x1f4
created by github.com/bcicen/ctop/connector/collector.(*DockerLogs).Stream
        /app/connector/collector/docker_logs.go:47 +0x278
```

**Comment by bcicen** [comment]
fix merged; to be included in v0.7.7
