### ISSUE TITLE
Panic when viewing details of a container which exits

### ISSUE THREAD

**Issue by tonsV2** [bcicen/ctop#274]
When I view the details of a container and that container exits it results in the below.

```
panic: runtime error: index out of range [1] with length 0 [recovered]
	panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main.panicExit()
	/app/main.go:137 +0x6b
panic(0xbb8660, 0xc00023f980)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/bcicen/ctop/cwidgets/single.(*Env).Set(0xc0005b6930, 0xc00050c000, 0x3be)
	/app/cwidgets/single/env.go:32 +0x399
github.com/bcicen/ctop/cwidgets/single.(*Single).SetMeta(0xc0000ba370, 0xc0002a0870)
	/app/cwidgets/single/main.go:58 +0x10b
github.com/bcicen/ctop/container.(*Container).SetUpdater(...)
	/app/container/main.go:53
main.SingleView(0x0)
	/app/grid.go:87 +0xeb
main.Display(0xc00009e280)
	/app/grid.go:246 +0x834
main.main()
	/app/main.go:111 +0x625
```

**Comment by tonsV2** [comment]
This only happens on a specific container of mine. I'll submit a better issue once I have a few more details to share
