### ISSUE TITLE
Segmentation violation when running ctop

### ISSUE THREAD

**Issue by manast** [bcicen/ctop#50]
Installed ctop via brew yesterday on Mac os. On some machines it works, on others it displays the ctop information table and then crashed with a segmentation fault. I dont know if it matters but this happened on swarm nodes:
```
manuel@Manuels-MBP ~ $ ctop -v
ctop version dev-build, build none
```

```
: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1283014]

goroutine 1110 [running]:
github.com/bcicen/ctop/cwidgets/compact.(*CompactGrid).Align(0xc42045f950)
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/cwidgets/compact/grid.go:30 +0x1f4
main.RedrawRows(0xc420417900)
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/grid.go:33 +0x18c
main.RefreshDisplay()
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/grid.go:65 +0x3a
main.Display.func9(0x1359ee7, 0x5, 0xc420155202, 0x9, 0x1359ee7, 0x5, 0x0, 0x0, 0x1309ec0, 0xc420155210, ...)
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/grid.go:116 +0x20
github.com/bcicen/ctop/vendor/github.com/gizak/termui.(*EvtStream).Loop.func1(0xc420016640, 0x1359ee7, 0x5, 0xc420155202, 0x9, 0x1359ee7, 0x5, 0x0, 0x0, 0x1309ec0, ...)
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/vendor/github.com/gizak/termui/events.go:251 +0xff
created by github.com/bcicen/ctop/vendor/github.com/gizak/termui.(*EvtStream).Loop
	/private/tmp/ctop-20170315-2262-1ohr1sm/ctop-0.5/src/github.com/bcicen/ctop/vendor/github.com/gizak/termui/events.go:253 +0x167
```

**Comment by bcicen** [comment]
Thanks for the details @manast. Can you confirm whether you're still experiencing this in the latest ctop version?

**Comment by manast** [comment]
in one of my swarms it now (version 0.5.1) hangs with black screen, is there any way to get some debug information?

**Comment by bcicen** [comment]
closing for now; feel free to reopen if segfault is still reproducible in latest version
